In [8]:
import os
import sys
cwd = os.getcwd()
src_dir = os.path.join(cwd, '..', '../src/')
sys.path.append(src_dir)
from dataloader.data_load import download_dataset, map_data

download_dataset('playground-series-s5e10', '../data', unzip=True)
mapping = map_data('../data')

Downloading playground-series-s5e10.zip to ../data

100%|██████████| 7.76M/7.76M [00:00<00:00, 1.63GB/s]

In [9]:
data = mapping

# 1. Report Rendering

In [10]:
from dqc.dqc import DQCLayer
dqc = DQCLayer()
validation_report = dqc.validation_report(data)
statistics_report = dqc.statistics_report(data)
report = dqc.render_report(validation_report=validation_report,
                          statistics_report=statistics_report)

# 2. Missing Values Report

In [11]:
report['validation_report']['missing_values']

                                          missings_percentage
table_name        column_name
sample_submission id                                      0.0
                  accident_risk                           0.0
test              id                                      0.0
                  road_type                               0.0
                  num_lanes                               0.0
                  curvature                               0.0
                  speed_limit                             0.0
                  lighting                                0.0
                  weather                                 0.0
                  road_signs_present                      0.0
                  public_road                             0.0
                  time_of_day                             0.0
                  holiday                                 0.0
                  school_season                           0.0
                  num_reported_accidents                  0.0
train             id                                      0.0
                  road_type                               0.0
                  num_lanes                               0.0
                  curvature                               0.0
                  speed_limit                             0.0
                  lighting                                0.0
                  weather                                 0.0
                  road_signs_present                      0.0
                  public_road                             0.0
                  time_of_day                             0.0
                  holiday                                 0.0
                  school_season                           0.0
                  num_reported_accidents                  0.0
                  accident_risk                           0.0

Luckily what we can observe is that there are missing values over any of the tables

# 3. Data Types Report

In [12]:
report['validation_report']['data_types']

                                         current_dtype inferred_dtype is_mixed
table_name        column_name
sample_submission id                             int64          int64    False
                  accident_risk                float64        float64    False
test              school_season                   bool           bool    False
                  holiday                         bool           bool    False
                  time_of_day                   object         object    False
                  public_road                     bool           bool    False
                  road_signs_present              bool           bool    False
                  weather                       object         object    False
                  num_reported_accidents         int64          int64    False
                  speed_limit                    int64          int64    False
                  curvature                    float64        float64    False
                  num_lanes                      int64          int64    False
                  road_type                     object         object    False
                  id                             int64          int64    False
                  lighting                      object         object    False
train             school_season                   bool           bool    False
                  holiday                         bool           bool    False
                  time_of_day                   object         object    False
                  public_road                     bool           bool    False
                  road_signs_present              bool           bool    False
                  weather                       object         object    False
                  curvature                    float64        float64    False
                  speed_limit                    int64          int64    False
                  num_lanes                      int64          int64    False
                  road_type                     object         object    False
                  id                             int64          int64    False
                  num_reported_accidents         int64          int64    False
                  lighting                      object         object    False
                  accident_risk                float64        float64    False

No mixed datatypes over all the tables

# 4. Unique Values Report

In [13]:
report['validation_report']['uniques']

                                          unique_values
table_name        column_name
sample_submission id                             172585
                  accident_risk                       1
test              id                             172585
                  road_type                           3
                  num_lanes                           4
                  curvature                         195
                  speed_limit                         5
                  lighting                            3
                  weather                             3
                  road_signs_present                  2
                  public_road                         2
                  time_of_day                         3
                  holiday                             2
                  school_season                       2
                  num_reported_accidents              8
train             id                             517754
                  road_type                           3
                  num_lanes                           4
                  curvature                         261
                  speed_limit                         5
                  lighting                            3
                  weather                             3
                  road_signs_present                  2
                  public_road                         2
                  time_of_day                         3
                  holiday                             2
                  school_season                       2
                  num_reported_accidents              8
                  accident_risk                      98

Most features do not have a lot of unique values, which gives an assumption that we are going to have some encoding job

# 5. Duplicates Report

In [14]:
report['validation_report']['duplicates']

                   duplicated_rows
sample_submission                0
test                             0
train                            0

No duplicates over all the tables

# 6. Consistency Report

In [15]:
report['validation_report']['consistency']

,relation,left_only,intersect,right_only
0,"sample_submission, test ON id",0,172585,0
1,"sample_submission, train ON accident_risk",1,0,98
2,"sample_submission, train ON id",172585,0,517754
3,"test, train ON curvature",37,158,103
4,"test, train ON school_season",0,2,0
5,"test, train ON weather",0,3,0
6,"test, train ON speed_limit",0,5,0
7,"test, train ON road_type",0,3,0
8,"test, train ON num_lanes",0,4,0
9,"test, train ON id",172585,0,517754
10,"test, train ON lighting",0,3,0
11,"test, train ON road_signs_present",0,2,0
12,"test, train ON time_of_day",0,3,0
13,"test, train ON holiday",0,2,0
14,"test, train ON num_reported_accidents",0,8,0
15,"test, train ON public_road",0,2,0

Despite the fact we see some missintersections in test and train with curvature, it will not cause aby trouble. So the data is consistent.

# 7. Statistics Report

In [16]:
report['statistics_report']['statistics']

                                             count           mean  \
table_name        column_name
sample_submission id                      172585.0  604046.000000
                  accident_risk           172585.0       0.352000
test              id                      172585.0  604046.000000
                  num_lanes               172585.0       2.494046
                  curvature               172585.0       0.487263
                  speed_limit             172585.0      46.102761
                  num_reported_accidents  172585.0       1.186059
train             id                      517754.0  258876.500000
                  num_lanes               517754.0       2.491511
                  curvature               517754.0       0.488719
                  speed_limit             517754.0      46.112575
                  num_reported_accidents  517754.0       1.187970
                  accident_risk           517754.0       0.352377

                                                   std         min  \
table_name        column_name
sample_submission id                      4.982114e+04  517754.000
                  accident_risk           5.551131e-17       0.352
test              id                      4.982114e+04  517754.000
                  num_lanes               1.119148e+00       1.000
                  curvature               2.723428e-01       0.000
                  speed_limit             1.578708e+01      25.000
                  num_reported_accidents  8.971609e-01       0.000
train             id                      1.494628e+05       0.000
                  num_lanes               1.120434e+00       1.000
                  curvature               2.725633e-01       0.000
                  speed_limit             1.578852e+01      25.000
                  num_reported_accidents  8.959612e-01       0.000
                  accident_risk           1.664171e-01       0.000

                                                  1%         25%         50%  \
table_name        column_name
sample_submission id                      519479.840  560900.000  604046.000
                  accident_risk                0.352       0.352       0.352
test              id                      519479.840  560900.000  604046.000
                  num_lanes                    1.000       1.000       2.000
                  curvature                    0.010       0.260       0.510
                  speed_limit                 25.000      35.000      45.000
                  num_reported_accidents       0.000       1.000       1.000
train             id                        5177.530  129438.250  258876.500
                  num_lanes                    1.000       1.000       2.000
                  curvature                    0.010       0.260       0.510
                  speed_limit                 25.000      35.000      45.000
                  num_reported_accidents       0.000       1.000       1.000
                  accident_risk                0.030       0.230       0.340

                                                 75%         99%         max
table_name        column_name
sample_submission id                      647192.000  688612.160  690338.000
                  accident_risk                0.352       0.352       0.352
test              id                      647192.000  688612.160  690338.000
                  num_lanes                    3.000       4.000       4.000
                  curvature                    0.710       0.980       1.000
                  speed_limit                 60.000      70.000      70.000
                  num_reported_accidents       2.000       3.000       7.000
train             id                      388314.750  512575.470  517753.000
                  num_lanes                    3.000       4.000       4.000
                  curvature                    0.710       0.980       1.000
                  speed_limit                 60.000      70.000      70.000
                  num_reported_accidents       2.000       3.000       7.000
                  accident_risk                0.460       0.780       1.000

# 8. Outliers Report

In [18]:
report['statistics_report']['outliers']

                                                  Q1          Q3        IQR  \
table             column
sample_submission id                      560900.000  647192.000   86292.00
                  accident_risk                0.352       0.352       0.00
test              id                      560900.000  647192.000   86292.00
                  num_lanes                    1.000       3.000       2.00
                  curvature                    0.260       0.710       0.45
                  speed_limit                 35.000      60.000      25.00
                  num_reported_accidents       1.000       2.000       1.00
train             id                      129438.250  388314.750  258876.50
                  num_lanes                    1.000       3.000       2.00
                  curvature                    0.260       0.710       0.45
                  speed_limit                 35.000      60.000      25.00
                  num_reported_accidents       1.000       2.000       1.00
                  accident_risk                0.230       0.460       0.23

                                          lower_bound  upper_bound  \
table             column
sample_submission id                       431462.000   776630.000
                  accident_risk                 0.352        0.352
test              id                       431462.000   776630.000
                  num_lanes                    -2.000        6.000
                  curvature                    -0.415        1.385
                  speed_limit                  -2.500       97.500
                  num_reported_accidents       -0.500        3.500
train             id                      -258876.500   776629.500
                  num_lanes                    -2.000        6.000
                  curvature                    -0.415        1.385
                  speed_limit                  -2.500       97.500
                  num_reported_accidents       -0.500        3.500
                  accident_risk                -0.115        0.805

                                          outliers_percentage     min_val  \
table             column
sample_submission id                                 0.000000  517754.000
                  accident_risk                      0.000000       0.352
test              id                                 0.000000  517754.000
                  num_lanes                          0.000000       1.000
                  curvature                          0.000000       0.000
                  speed_limit                        0.000000      25.000
                  num_reported_accidents             0.535968       0.000
train             id                                 0.000000       0.000
                  num_lanes                          0.000000       1.000
                  curvature                          0.000000       0.000
                  speed_limit                        0.000000      25.000
                  num_reported_accidents             0.511633       0.000
                  accident_risk                      0.650309       0.000

                                             max_val  1%_percentile  \
table             column
sample_submission id                      690338.000     519479.840
                  accident_risk                0.352          0.352
test              id                      690338.000     519479.840
                  num_lanes                    4.000          1.000
                  curvature                    1.000          0.010
                  speed_limit                 70.000         25.000
                  num_reported_accidents       7.000          0.000
train             id                      517753.000       5177.530
                  num_lanes                    4.000          1.000
                  curvature                    1.000          0.010
                  speed_limit                 70.000         25.000
                  num_reported_accidents       7.000          0.000
                  accident_risk                1.000          0.030

                                          99%_percentile
table             column
sample_submission id                          688612.160
                  accident_risk                    0.352
test              id                          688612.160
                  num_lanes                        4.000
                  curvature                        0.980
                  speed_limit                     70.000
                  num_reported_accidents           3.000
train             id                          512575.470
                  num_lanes                        4.000
                  curvature                        0.980
                  speed_limit                     70.000
                  num_reported_accidents           3.000
                  accident_risk                    0.780

Well, see some kind of outliers in *num_reported_accidents* and *accident_risk*, though I guess we'll not restrict the values due to the fact that this might be useful for the model to be able to predict this extreme values